[package]
name = "locale-config"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[features]
default = []
e2e = []

[dependencies]
dirs.workspace = true
serde_json.workspace = true
shared-types = { path = "../shared-types" }
thiserror.workspace = true
toml_edit.workspace = true
tracing.workspace = true

[dev-dependencies]
tempfile.workspace = true

[lints]
workspace = true
