[package]
name = "msix-links"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
anyhow.workspace = true
chrono.workspace = true
downloader = { path = "../../crates/downloader" }
serde.workspace = true
serde_json.workspace = true
shared-types = { path = "../../crates/shared-types" }
tokio.workspace = true
url.workspace = true

[lints]
workspace = true
