[package]
name = "remote-config"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
base64.workspace = true
chrono.workspace = true
ed25519-dalek.workspace = true
reqwest.workspace = true
rustls.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
shared-types = { path = "../shared-types" }
thiserror.workspace = true
tokio.workspace = true
tracing.workspace = true
url.workspace = true

[dev-dependencies]
rcgen.workspace = true
tempfile.workspace = true
uuid.workspace = true

[lints]
workspace = true
